# Generated by Django 5.2.3 on 2025-07-05 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menstruation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstruations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'start', 'end'), name='unique_user_start_end', violation_error_message='사용자는 월경을 같은 기간에 한 번만 할 수 있습니다.')],
            },
        ),
    ]
