# Generated by Django 5.2.3 on 2025-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='혜린', max_length=10),
            preserve_default=False,
        ),
    ]
