# Generated by Django 5.2.3 on 2025-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditionreviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '😢'), (2, '😡'), (3, '😌'), (4, '🙂'), (5, '😁')]),
        ),
    ]
