# Generated by Django 5.2.3 on 2025-07-04 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('duration', models.DurationField()),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '전신'), (2, '상체'), (3, '하체'), (4, '코어')])),
                ('image', models.ImageField(upload_to='exercise/image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_routine', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('exercise_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_review', to='exercises.exercisehistory')),
            ],
        ),
        migrations.CreateModel(
            name='ReactedExerciseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emoji', models.PositiveSmallIntegerField(choices=[(1, '😍'), (2, '😊'), (3, '🤣'), (4, '😢'), (5, '😲')])),
                ('exercise_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='exercises.exercisereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacted_exercise_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedExerciseRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_routine', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapped_exercise_routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exercisehistory',
            constraint=models.UniqueConstraint(fields=('user', 'created_at'), name='사용자는 운동을 같은 시각에 한 번만 합니다.'),
        ),
        migrations.AddConstraint(
            model_name='reactedexercisereview',
            constraint=models.UniqueConstraint(fields=('user', 'exercise_review'), name='사용자는 운동 리뷰 반응을 한 번만 남깁니다.'),
        ),
        migrations.AddConstraint(
            model_name='scrappedexerciseroutine',
            constraint=models.UniqueConstraint(fields=('user', 'exercise_routine'), name='사용자는 동일한 운동 루틴을 한 번만 스크랩합니다.'),
        ),
    ]
