# Generated by Django 5.2.3 on 2025-07-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisehistory',
            options={'ordering': ['exercised_at', 'order']},
        ),
        migrations.AlterModelOptions(
            name='scrappedexerciseroutine',
            options={'ordering': ['scrapped_at', 'order']},
        ),
    ]
