# Generated by Django 5.2.3 on 2025-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercisehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactedexercisereview',
            name='emoji',
            field=models.PositiveSmallIntegerField(choices=[(1, '😢'), (2, '😡'), (3, '😌'), (4, '🙂'), (5, '😁')]),
        ),
    ]
