# Generated by Django 5.2.3 on 2025-07-04 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '친구 요청'), (2, '친구 요청을 수락'), (3, '친구 요청을 거절'), (4, '운동 리뷰에 반응'), (5, '콕 찌르기')])),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receivings', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sendings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
